class Autogenerated {
  String? status;
  ResponseData? response;

  Autogenerated({this.status, this.response});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    response = json['response'] != null
        ? ResponseData.fromJson(json['response'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['status'] = status;
    if (response != null) {
      data['response'] = response!.toJson();
    }
    return data;
  }
}

class ResponseData {
  String? message;
  Data? data;

  ResponseData({this.message, this.data});

  ResponseData.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  String? userid;
  String? mobile;
  String? offerdata;

  Data({this.userid, this.mobile, this.offerdata});

  Data.fromJson(Map<String, dynamic> json) {
    userid = json['userid'];
    mobile = json['mobile'];
    offerdata = json['offerdata'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['userid'] = userid;
    data['mobile'] = mobile;
    data['offerdata'] = offerdata;
    return data;
  }
}
